# Generated by Django 2.2.5 on 2021-05-15 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontent',
            options={'verbose_name': 'Контент главной страницы', 'verbose_name_plural': 'Контент главной страницы'},
        ),
        migrations.AddField(
            model_name='homecontent',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 15), verbose_name='Дата'),
        ),
    ]
