# Generated by Django 2.2.5 on 2021-05-18 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210515_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 18), verbose_name='Дата'),
        ),
    ]
