# Generated by Django 2.2.5 on 2021-05-22 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210522_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencesContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Заголовок по-умолчанию', max_length=50, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Контент страницы конференций',
                'verbose_name_plural': 'Контент страницы конференций',
            },
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='full_text',
            field=models.TextField(verbose_name='Контент блока'),
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.CreateModel(
            name='ConferencesBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подзаголовок блока информации')),
                ('full_text', models.TextField(verbose_name='Контент блока')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('date', models.DateTimeField(default=datetime.date(2021, 5, 22), verbose_name='Дата')),
                ('ConferencesContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ConferencesContent')),
            ],
        ),
    ]
