# Generated by Django 2.2.5 on 2021-05-22 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210522_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 22), verbose_name='Дата'),
        ),
    ]
