# Generated by Django 2.2.5 on 2021-05-22 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210522_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceProgressContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Заголовок по-умолчанию', max_length=50, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Контент страницы достижений',
                'verbose_name_plural': 'Контент страницы достижений',
            },
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 23), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='conferencesblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 23), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 23), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='ScienceProgressBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подзаголовок блока информации')),
                ('full_text', models.TextField(verbose_name='Контент блока')),
                ('date', models.DateField(default=datetime.date(2021, 5, 23), verbose_name='Дата')),
                ('ScienceProgressContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ScienceProgressContent')),
            ],
        ),
    ]
