# Generated by Django 2.2.5 on 2021-05-23 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210523_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подзаголовок блока информации')),
                ('date', models.DateField(default=datetime.date(2021, 5, 24), verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Список публикаций',
                'verbose_name_plural': 'Списки публикаций',
            },
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 24), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='conferencesblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 24), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 24), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='scienceprogressblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 24), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='PublicationsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Наименование публикации')),
                ('authors_publications', models.TextField(verbose_name='Авторы')),
                ('last_text', models.TextField(verbose_name='Другая информация')),
                ('source', models.CharField(max_length=50, verbose_name='Ссылка на публикацию')),
                ('file', models.FileField(default='PDF/', upload_to='PDF/', verbose_name='Файл')),
                ('date', models.DateField(default=datetime.date(2021, 5, 24), verbose_name='Дата')),
                ('PublicationsBlock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PublicationsContent')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
