# Generated by Django 2.2.5 on 2021-05-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210524_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographyblock',
            name='full_text_en',
            field=models.TextField(null=True, verbose_name='Контент блока'),
        ),
        migrations.AddField(
            model_name='biographyblock',
            name='full_text_ru',
            field=models.TextField(null=True, verbose_name='Контент блока'),
        ),
        migrations.AddField(
            model_name='biographyblock',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AddField(
            model_name='biographyblock',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AddField(
            model_name='biographycontent',
            name='main_title_en',
            field=models.CharField(default='Заголовок по-умолчанию', max_length=50, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='biographycontent',
            name='main_title_ru',
            field=models.CharField(default='Заголовок по-умолчанию', max_length=50, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='conferencesblock',
            name='full_text_en',
            field=models.TextField(null=True, verbose_name='Контент блока'),
        ),
        migrations.AddField(
            model_name='conferencesblock',
            name='full_text_ru',
            field=models.TextField(null=True, verbose_name='Контент блока'),
        ),
        migrations.AddField(
            model_name='conferencesblock',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AddField(
            model_name='conferencesblock',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AddField(
            model_name='conferencescontent',
            name='main_title_en',
            field=models.CharField(default='Заголовок по-умолчанию', max_length=50, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='conferencescontent',
            name='main_title_ru',
            field=models.CharField(default='Заголовок по-умолчанию', max_length=50, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='full_text_en',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='full_text_ru',
            field=models.TextField(null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='publicationsblock',
            name='authors_publications_en',
            field=models.TextField(null=True, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='publicationsblock',
            name='authors_publications_ru',
            field=models.TextField(null=True, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='publicationsblock',
            name='last_text_en',
            field=models.TextField(null=True, verbose_name='Другая информация'),
        ),
        migrations.AddField(
            model_name='publicationsblock',
            name='last_text_ru',
            field=models.TextField(null=True, verbose_name='Другая информация'),
        ),
        migrations.AddField(
            model_name='publicationsblock',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Наименование публикации'),
        ),
        migrations.AddField(
            model_name='publicationsblock',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Наименование публикации'),
        ),
        migrations.AddField(
            model_name='scienceprogressblock',
            name='full_text_en',
            field=models.TextField(null=True, verbose_name='Контент блока'),
        ),
        migrations.AddField(
            model_name='scienceprogressblock',
            name='full_text_ru',
            field=models.TextField(null=True, verbose_name='Контент блока'),
        ),
        migrations.AddField(
            model_name='scienceprogressblock',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AddField(
            model_name='scienceprogressblock',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AddField(
            model_name='scienceprogresscontent',
            name='main_title_en',
            field=models.CharField(default='Заголовок по-умолчанию', max_length=50, null=True, verbose_name='Заголовок страницы'),
        ),
        migrations.AddField(
            model_name='scienceprogresscontent',
            name='main_title_ru',
            field=models.CharField(default='Заголовок по-умолчанию', max_length=50, null=True, verbose_name='Заголовок страницы'),
        ),
    ]
