# Generated by Django 2.2.5 on 2021-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210524_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesblock',
            name='image',
        ),
        migrations.AddField(
            model_name='conferencesblock',
            name='link_image',
            field=models.CharField(default='/', max_length=100, verbose_name='Изображение'),
        ),
    ]
