# Generated by Django 2.2.5 on 2021-05-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210524_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesblock',
            name='link_image',
            field=models.CharField(default='/', max_length=200, verbose_name='Изображение'),
        ),
    ]
