# Generated by Django 2.2.5 on 2021-05-25 00:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210524_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(default='Заголовок по-умолчанию', max_length=50, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Контент страницы проектов',
                'verbose_name_plural': 'Контент страницы проектов',
            },
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 25), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='conferencesblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 25), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='conferencesblock',
            name='link_image',
            field=models.CharField(default='/', max_length=200, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 25), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='publicationsblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 25), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='publicationscontent',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 25), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='scienceprogressblock',
            name='date',
            field=models.DateField(default=datetime.date(2021, 5, 25), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='ProjectsBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подзаголовок блока информации')),
                ('full_text', models.TextField(verbose_name='Контент блока')),
                ('link_image', models.CharField(default='/', max_length=200, verbose_name='Ссылка на изображение')),
                ('date', models.DateField(default=datetime.date(2021, 5, 25), verbose_name='Дата')),
                ('ProjectsContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProjectsContent')),
            ],
        ),
    ]
