# Generated by Django 2.2.5 on 2021-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210527_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navcontent',
            name='link_logo_image',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ссылка на фотографию'),
        ),
    ]
