# Generated by Django 2.2.5 on 2021-05-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210527_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementblock',
            name='block_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='achievementblock',
            name='block_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='achievementblock',
            name='block_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='block_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='block_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='biographyblock',
            name='block_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='courseblock',
            name='block_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='courseblock',
            name='block_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='courseblock',
            name='block_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video_name',
            field=models.CharField(max_length=100, verbose_name='Наименование видео'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование видео'),
        ),
        migrations.AlterField(
            model_name='coursevideo',
            name='video_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование видео'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='block_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='block_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='block_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='navcontent',
            name='link_logo_image',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка на фотографию'),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='block_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='block_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='projectblock',
            name='block_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(max_length=100, verbose_name='Ссылка на публикацию'),
        ),
        migrations.AlterField(
            model_name='publicationblock',
            name='block_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='publicationblock',
            name='block_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='publicationblock',
            name='block_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
    ]
