# Generated by Django 2.2.5 on 2021-05-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210530_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceblock',
            name='block_title',
            field=models.CharField(max_length=100, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='conferenceblock',
            name='block_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='conferenceblock',
            name='block_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Подзаголовок блока информации'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(max_length=300, verbose_name='Ссылка на публикацию'),
        ),
    ]
